[tool.black]
line-length = 79
exclude = '''
(
    ^/\..*
  | ^/docs/
  | ^/github2pypi/
  | ^/tests/
)
'''

[tool.isort]
atomic = true
force_single_line = true
force_sort_within_sections = true
skip_glob = 'src/*, .anaconda3/*'
